AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple SAM template for a Lambda function

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MySampleFunction
      Handler: app.lambda_handler   # Adjust based on your code
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
